/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ConnectionCheckRouteImport } from './routes/connection-check'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FlightClaimsRouteImport } from './routes/flight-claims'
import { Route as InsuranceAppealRouteImport } from './routes/insurance-appeal'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ArticlesSlugRouteImport } from './routes/articles_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionCheckRoute = ConnectionCheckRouteImport.update({
  id: '/connection-check',
  path: '/connection-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightClaimsRoute = FlightClaimsRouteImport.update({
  id: '/flight-claims',
  path: '/flight-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceAppealRoute = InsuranceAppealRouteImport.update({
  id: '/insurance-appeal',
  path: '/insurance-appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles_/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/connection-check': typeof ConnectionCheckRoute
  '/corrections': typeof CorrectionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/flight-claims': typeof FlightClaimsRoute
  '/insurance-appeal': typeof InsuranceAppealRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/connection-check': typeof ConnectionCheckRoute
  '/corrections': typeof CorrectionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/flight-claims': typeof FlightClaimsRoute
  '/insurance-appeal': typeof InsuranceAppealRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/articles/$slug': typeof ArticlesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/connection-check': typeof ConnectionCheckRoute
  '/corrections': typeof CorrectionsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/flight-claims': typeof FlightClaimsRoute
  '/insurance-appeal': typeof InsuranceAppealRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/articles_/$slug': typeof ArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/connection-check'
    | '/corrections'
    | '/disclaimer'
    | '/flight-claims'
    | '/insurance-appeal'
    | '/privacy-policy'
    | '/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/connection-check'
    | '/corrections'
    | '/disclaimer'
    | '/flight-claims'
    | '/insurance-appeal'
    | '/privacy-policy'
    | '/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/connection-check'
    | '/corrections'
    | '/disclaimer'
    | '/flight-claims'
    | '/insurance-appeal'
    | '/privacy-policy'
    | '/articles_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRoute
  ConnectionCheckRoute: typeof ConnectionCheckRoute
  CorrectionsRoute: typeof CorrectionsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FlightClaimsRoute: typeof FlightClaimsRoute
  InsuranceAppealRoute: typeof InsuranceAppealRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection-check': {
      id: '/connection-check'
      path: '/connection-check'
      fullPath: '/connection-check'
      preLoaderRoute: typeof ConnectionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-claims': {
      id: '/flight-claims'
      path: '/flight-claims'
      fullPath: '/flight-claims'
      preLoaderRoute: typeof FlightClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-appeal': {
      id: '/insurance-appeal'
      path: '/insurance-appeal'
      fullPath: '/insurance-appeal'
      preLoaderRoute: typeof InsuranceAppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/$slug': {
      id: '/articles_/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRoute,
  ConnectionCheckRoute: ConnectionCheckRoute,
  CorrectionsRoute: CorrectionsRoute,
  DisclaimerRoute: DisclaimerRoute,
  FlightClaimsRoute: FlightClaimsRoute,
  InsuranceAppealRoute: InsuranceAppealRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
